resolver: lts-10.3
packages:
- '.'
- '../../libs/bilge'
- '../../libs/metrics-core'
- '../../libs/metrics-wai'
- '../../libs/types-common'
- '../../libs/gundeck-types'
- '../../libs/wai-utilities'
flags:
  types-common:
    protobuf: True
    arbitrary: True
extra-deps:
- data-timeout-0.3
extra-package-dbs: []
