extra-package-dbs: []
packages:
- .
- '../../libs/brig-types'
- '../../libs/types-common'
- '../../libs/bilge'
- '../../libs/cargohold-types'
- '../../libs/cassandra-util'
- '../../libs/gundeck-types'
- '../../libs/ropes'
- '../../libs/tasty-cannon'
- '../../libs/galley-types'
- '../../libs/http-client-openssl-ext'
- '../../libs/metrics-core'
- '../../libs/metrics-wai'
- '../../libs/sodium-crypto-sign'
- '../../libs/wai-utilities'
- '../../libs/zauth'
- location:
    git: https://github.com/tiago-loureiro/haskell-multihash.git
    commit: 7622cfcff97fa1e207ec91bb11495a207e6c0195
  extra-dep: true
- location:
    git: https://github.com/wireapp/cryptobox-haskell
    commit: 7546a1a25635ef65183e3d44c1052285e8401608
  extra-dep: true

flags:
  types-common:
    cql: True
    protobuf: True
    arbitrary: True

extra-deps:
- base58-bytestring-0.1.0
- currency-codes-2.0.0.0
- data-timeout-0.3
- geoip2-0.3.1.0
- html-entities-1.1.4.1
- mime-0.4.0.2
- tasty-1.0.0.1
- text-icu-translit-0.1.0.7
- wai-middleware-gunzip-0.0.2
- HsOpenSSL-0.11.4.12
resolver: lts-10.3
